DROP TABLE IF EXISTS Orders;

DROP TABLE IF EXISTS Client;

DROP TABLE IF EXISTS TenerifePlus;

DROP TABLE IF EXISTS Historical;

DROP TABLE IF EXISTS Employee;

DROP TABLE IF EXISTS Product_Vivero;

DROP TABLE IF EXISTS Zone;

DROP TABLE IF EXISTS Product;

DROP TABLE IF EXISTS Vivero;