
\i INSERT_SCRIPTS/INSERT_VIVERO.sql;
\i INSERT_SCRIPTS/INSERT_CLIENT.sql;
\i INSERT_SCRIPTS/INSERT_CLIENT_PLUS.sql
\i INSERT_SCRIPTS/INSERT_PRODUCT.sql;
\i INSERT_SCRIPTS/INSERT_PRODUCT-VIVERO.sql;
\i INSERT_SCRIPTS/INSERT_ZONE.sql;
\i INSERT_SCRIPTS/INSERT_EMPLOYEE.sql
\i INSERT_SCRIPTS/INSERT_HISTORICAL.sql
\i INSERT_SCRIPTS/INSERT_ORDERS.sql