-- Cliente Plus 1
INSERT INTO
    TenerifePlus (
        name,
        last_name_1,
        last_name_2,
        email,
        registration_date
    )
VALUES
    (
        'Laura',
        'Hernández',
        'Jiménez',
        'laura.hernandez@example.com',
        '2023-10-30'
    ),
    (
        'Francisco',
        'Martínez',
        'López',
        'francisco.martinez@example.com',
        '2023-10-29'
    ),
    (
        'Elena',
        'Fernández',
        'García',
        'elena.fernandez@example.com',
        '2023-10-28'
    ),
    (
        'Miguel',
        'Sánchez',
        'Pérez',
        'miguel.sanchez@example.com',
        '2023-10-27'
    ),
    (
        'Isabel',
        'Gómez',
        'Díaz',
        'isabel.gomez@example.com',
        '2023-10-26'
    );